# Generated by Django 3.0.4 on 2020-05-14 01:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_name', models.CharField(max_length=300)),
                ('total_records', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='packet_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(max_length=50)),
                ('results', models.CharField(max_length=300)),
                ('capture_buffers', models.ManyToManyField(to='TRFC_VSLZR.module')),
            ],
        ),
        migrations.CreateModel(
            name='uploaded_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300)),
                ('filename', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('json', models.FileField(upload_to='.')),
            ],
        ),
        migrations.CreateModel(
            name='result_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(blank=True, null=True)),
                ('parent_capture_buffer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TRFC_VSLZR.module')),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TRFC_VSLZR.uploaded_file')),
                ('parent_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRFC_VSLZR.packet_record')),
            ],
        ),
        migrations.AddField(
            model_name='packet_record',
            name='parent_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRFC_VSLZR.uploaded_file'),
        ),
        migrations.AddField(
            model_name='module',
            name='parent_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRFC_VSLZR.uploaded_file'),
        ),
    ]
