# Generated by Django 3.0.4 on 2020-05-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRFC_VSLZR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='buffer_name',
            new_name='module_name',
        ),
        migrations.RenameField(
            model_name='packet_record',
            old_name='capture_buffers',
            new_name='modules',
        ),
        migrations.RenameField(
            model_name='result_output',
            old_name='parent_capture_buffer',
            new_name='parent_module',
        ),
    ]
