# Generated by Django 3.0.4 on 2020-05-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRFC_VSLZR', '0003_result_output_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_num',
            field=models.IntegerField(null=True),
        ),
    ]
